import {
    SiTypescript,
    SiJavascript,
    SiC,
    SiPython,
    SiGnubash,
    SiJson,
    SiMysql,
    SiReact,
    SiNextdotjs,
    SiVite,
    SiBootstrap,
    SiTailwindcss,
    SiGooglecloud,
    SiVercel,
    SiSentry,
    SiRedux,
    SiWordpress,
    SiGit,
    SiKubernetes,
    SiDocker,
    SiSocketdotio,
    SiJira,
    SiGithubcopilot,
    SiFigma,
    SiFastapi
} from "react-icons/si";

export const tools = [
    { name: "Typescript", Icon: SiTypescript },
    { name: "Javascript", Icon: SiJavascript },
    { name: "FastAPI", Icon: SiFastapi },
    { name: "C/C++", Icon: SiC },
    { name: "Python", Icon: SiPython },
    { name: "Bash", Icon: SiGnubash },
    { name: "JSON", Icon: SiJson },
    { name: "SQL", Icon: SiMysql },
    { name: "React", Icon: SiReact },
    { name: "Next.js", Icon: SiNextdotjs },
    { name: "Vite", Icon: SiVite },
    { name: "Bootstrap", Icon: SiBootstrap },
    { name: "Tailwind", Icon: SiTailwindcss },
    { name: "Google Cloud", Icon: SiGooglecloud },
    { name: "Vercel", Icon: SiVercel },
    { name: "Sentry", Icon: SiSentry },
    { name: "Redux", Icon: SiRedux },
    { name: "Wordpress", Icon: SiWordpress },
    { name: "Git", Icon: SiGit },
    { name: "Kubernetes", Icon: SiKubernetes },
    { name: "Docker", Icon: SiDocker },
    { name: "Websockets", Icon: SiSocketdotio },
    { name: "Jira", Icon: SiJira },
    { name: "Copilot", Icon: SiGithubcopilot },
    { name: "Figma", Icon: SiFigma }
];