import {
    SiTypescript,
    SiJavascript,
    SiC,
    SiPython,
    SiGnubash,
    SiJson,
    SiMysql,
    SiReact,
    SiNextdotjs,
    SiVite,
    SiBootstrap,
    SiTailwindcss,
    SiGooglecloud,
    SiVercel,
    SiSentry,
    SiRedux,
    SiWordpress,
    SiGit,
    SiKubernetes,
    SiDocker,
    SiSocketdotio,
    SiJira,
    SiGithubcopilot,
    SiFigma,
    SiFastapi,
    SiGoogle,
    SiSage,
    SiHelm,
    SiPostman,
    SiSelenium,
    SiAuth0,
    SiYarn,
    SiLinux,
    SiUbuntu
} from "react-icons/si";
import { SliderItem } from "./types";

export const tools: SliderItem[] = [
    { name: "Typescript", Icon: SiTypescript, type: "frontend", yearsExperience: 4, mastery: 'Expert' },
    { name: "Javascript", Icon: SiJavascript, type: "frontend", yearsExperience: 6, mastery: 'Expert' },
    { name: "FastAPI", Icon: SiFastapi, type: "backend", yearsExperience: 2 },
    { name: "C/C++", Icon: SiC, type: "backend", yearsExperience: 6 },
    { name: "Python", Icon: SiPython, type: "backend", yearsExperience: 6, mastery: 'Expert' },
    { name: "Bash", Icon: SiGnubash, type: "other", yearsExperience: 3, mastery: 'Expert' },
    { name: "JSON", Icon: SiJson, type: "backend", yearsExperience: 6 },
    { name: "SQL", Icon: SiMysql, type: "backend", yearsExperience: 4, mastery: 'Proficient' },
    { name: "React", Icon: SiReact, type: "frontend", yearsExperience: 4, mastery: 'Expert' },
    { name: "Next.js", Icon: SiNextdotjs, type: "frontend", yearsExperience: 2, mastery: 'Proficient' },
    { name: "Vite", Icon: SiVite, type: "frontend", yearsExperience: 4 },
    { name: "Bootstrap", Icon: SiBootstrap, type: "frontend", yearsExperience: 6, mastery: 'Expert' },
    { name: "Tailwind", Icon: SiTailwindcss, type: "frontend", yearsExperience: 6, mastery: 'Expert' },
    { name: "Google Cloud", Icon: SiGooglecloud, type: "backend", yearsExperience: 5, mastery: 'Expert' },
    { name: "Vercel", Icon: SiVercel, type: "backend", yearsExperience: 2, mastery: 'Proficient' },
    { name: "Sentry", Icon: SiSentry, type: "other", yearsExperience: 2, mastery: 'Proficient' },
    { name: "Redux", Icon: SiRedux, type: "frontend", yearsExperience: 2, mastery: 'Proficient' },
    { name: "Wordpress", Icon: SiWordpress, type: "backend", yearsExperience: 6, mastery: 'Expert' },
    { name: "Git", Icon: SiGit, type: "other", yearsExperience: 8, mastery: 'Expert' },
    { name: "Kubernetes", Icon: SiKubernetes, type: "backend", yearsExperience: 4, mastery: 'Novice' },
    { name: "Docker", Icon: SiDocker, type: "backend", yearsExperience: 6, mastery: 'Expert' },
    { name: "Websockets", Icon: SiSocketdotio, type: "backend", yearsExperience: 5, mastery: 'Expert' },
    { name: "Jira", Icon: SiJira, type: "other", yearsExperience: 6, mastery: 'Proficient' },
    { name: "Copilot", Icon: SiGithubcopilot, type: "other" },
    { name: "Figma", Icon: SiFigma, type: "frontend", yearsExperience: 8, mastery: 'Expert' },
    { name: "GTM", Icon: SiGoogle, type: "other", yearsExperience: 5, mastery: 'Expert' },
    { name: "Cursor", Icon: SiSage, type: "other" },
    { name: "Helm", Icon: SiHelm, type: "backend", yearsExperience: 1, mastery: 'Novice' },
    { name: "Postman", Icon: SiPostman, type: "backend", yearsExperience: 4, mastery: 'Proficient' },
    { name: "Selenium", Icon: SiSelenium, type: "other", yearsExperience: 2, mastery: 'Proficient' },
    { name: "Yarn", Icon: SiYarn, type: "frontend", yearsExperience: 5, mastery: 'Proficient' },
    { name: "Linux", Icon: SiLinux, type: "other", yearsExperience: 15, mastery: 'Expert' },
    { name: "Ubuntu", Icon: SiUbuntu, type: "other", yearsExperience: 15, mastery: 'Expert' }
];
