import {
    SiTypescript,
    SiJavascript,
    SiC,
    SiPython,
    SiGnubash,
    SiJson,
    SiMysql,
    SiReact,
    SiNextdotjs,
    SiVite,
    SiBootstrap,
    SiTailwindcss,
    SiGooglecloud,
    SiVercel,
    SiSentry,
    SiRedux,
    SiWordpress,
    SiGit,
    SiKubernetes,
    SiDocker,
    SiSocketdotio,
    SiJira,
    SiGithubcopilot,
    SiFigma,
    SiFastapi,
    SiGoogle,
    SiSage,
    SiHelm
} from "react-icons/si";
import { SliderItem } from "./types";

export const tools: SliderItem[] = [
    { name: "Typescript", Icon: SiTypescript, type: "frontend" },
    { name: "Javascript", Icon: SiJavascript, type: "frontend" },
    { name: "FastAPI", Icon: SiFastapi, type: "backend" },
    { name: "C/C++", Icon: SiC, type: "backend" },
    { name: "Python", Icon: SiPython, type: "backend" },
    { name: "Bash", Icon: SiGnubash, type: "other" },
    { name: "JSON", Icon: SiJson, type: "backend" },
    { name: "SQL", Icon: SiMysql, type: "backend" },
    { name: "React", Icon: SiReact, type: "frontend" },
    { name: "Next.js", Icon: SiNextdotjs, type: "frontend" },
    { name: "Vite", Icon: SiVite, type: "frontend" },
    { name: "Bootstrap", Icon: SiBootstrap, type: "frontend" },
    { name: "Tailwind", Icon: SiTailwindcss, type: "frontend" },
    { name: "Google Cloud", Icon: SiGooglecloud, type: "backend" },
    { name: "Vercel", Icon: SiVercel, type: "backend" },
    { name: "Sentry", Icon: SiSentry, type: "other" },
    { name: "Redux", Icon: SiRedux, type: "frontend" },
    { name: "Wordpress", Icon: SiWordpress, type: "backend" },
    { name: "Git", Icon: SiGit, type: "other" },
    { name: "Kubernetes", Icon: SiKubernetes, type: "backend" },
    { name: "Docker", Icon: SiDocker, type: "backend" },
    { name: "Websockets", Icon: SiSocketdotio, type: "backend" },
    { name: "Jira", Icon: SiJira, type: "other" },
    { name: "Copilot", Icon: SiGithubcopilot, type: "other" },
    { name: "Figma", Icon: SiFigma, type: "frontend" },
    { name: "GTM", Icon: SiGoogle, type: "other" },
    { name: "Cursor", Icon: SiSage, type: "other" },
    { name: "Helm", Icon: SiHelm, type: "backend" }
];
